"scope: frontend":
- changed-files:
  - any-glob-to-any-file:
    - frontend/**/*

"scope: backend":
- changed-files:
  - any-glob-to-any-file:
    - backend/**/*
    - tests/**/*
    - migrations/**/*
    - manage.py
    - pyproject.toml

"scope: infrastructure":
- changed-files:
  - any-glob-to-any-file:
    - .circleci/*
    - .github/**/*
    - scripts/aws/**/*
    - scripts/docker/**/*
    - scripts/install/**/*
    - docker-*.yml

"dependencies":
- changed-files:
  - any-glob-to-any-file:
    - frontend/yarn.lock
    - pyproject.toml

"scope: translations":
- changed-files:
  - any-glob-to-any-file:
    - frontend/src/locales/*
