sonar.projectKey=escarabajo-rinoceronte_gestor-tareas-pruebas
sonar.organization=escarabajo-rinoceronte

# Rutas del código fuente
sonar.sources=backend,frontend

# Rutas exclusivas para pruebas
sonar.tests=tests,frontend/e2e,frontend/src/tests

# Exclusiones (No reducir el porcentaje de calidad por código de terceros o autogenerado)
sonar.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/venv/**,**/migrations/**,frontend/build/**,**/.github/**,**/docs/**

# Lenguajes
sonar.language=py,js

# Configuración específica de Python
sonar.python.version=3.10
