FROM node:16

WORKDIR /usr/src/app/frontend

COPY frontend /usr/src/app/frontend/

## Install dependencies
RUN npm install

# SERVE as a development 
# Is a dev dockerfile, runs npm install on every startup through CMD

CMD ["sh", "-c", "npm install && npm start"]