locals {
  account_name    = "hotosm"
  aws_profile     = "default"
  aws_region      = "us-east-1"
  team            = "hotosm"
  owner           = "HOTOSM"
  environment     = "staging"
  project         = "tasking-manager"
  application     = "tasking-manager"
  short_name      = "tm"
  maintainer      = "dev@hotosm.org"
  url             = "https://tasks-stage.hotosm.org"
  documentation   = "https://hotosm.github.io"
  IaC_Management  = "Terraform/Terragrunt"
  cost_center     = "False"
  version         = "4.8.2"
}