"""empty message

Revision ID: 05f1b650ddbc
Revises: 3b8b0956b217
Create Date: 2022-08-17 15:58:37.118728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05f1b650ddbc"
down_revision = "3b8b0956b217"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("banner")
    # ### end Alembic commands ###
