"""empty message

Revision ID: 0b9621f50c1f
Revises: 64b682d53e23
Create Date: 2017-06-26 09:37:24.950538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9621f50c1f'
down_revision = '64b682d53e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_geometry', 'projects', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_geometry', table_name='projects')
    # ### end Alembic commands ###
