"""empty message

Revision ID: 0e05f0fb4050
Revises: deec8123583d
Create Date: 2018-09-26 09:43:00.698966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e05f0fb4050'
down_revision = 'deec8123583d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_files', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_project_files_project_id', table_name='project_files')
    op.drop_constraint('project_files_path_file_name_key', 'project_files', type_='unique')
    op.create_unique_constraint(None, 'project_files', ['path'])
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.drop_constraint(None, 'project_files', type_='unique')
    op.create_unique_constraint('project_files_path_file_name_key', 'project_files', ['path', 'file_name'])
    op.create_index('ix_project_files_project_id', 'project_files', ['project_id'], unique=False)
    op.alter_column('project_files', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
