"""empty message

Revision ID: 11d39319af59
Revises: d357fe2dd332
Create Date: 2017-04-20 17:22:06.179155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer

# revision identifiers, used by Alembic.
revision = '11d39319af59'
down_revision = 'd357fe2dd332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tasks_bad_imagery', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('projects_mapped', sa.ARRAY(Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'projects_mapped')
    op.drop_column('projects', 'tasks_bad_imagery')
    # ### end Alembic commands ###
