"""empty message

Revision ID: 14842761654b
Revises: ba778ef9c615
Create Date: 2020-11-11 07:18:58.675778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14842761654b"
down_revision = "ba778ef9c615"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_custom_editors", "enabled")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_custom_editors",
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE project_custom_editors SET enabled = false")
    op.alter_column("project_custom_editors", "enabled", nullable=False)
    # ### end Alembic commands ###
