"""empty message

Revision ID: 1579d24928e7
Revises: 55790eeec3bf
Create Date: 2020-05-29 09:55:16.565573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1579d24928e7"
down_revision = "55790eeec3bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "entities_to_map")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("entities_to_map", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
