"""empty message

Revision ID: 19b1a02b3f91
Revises: badf8bb7d56b
Create Date: 2019-06-11 21:03:21.891208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b1a02b3f91'
down_revision = 'badf8bb7d56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['invalidator_id', 'is_closed'], unique=False)
    op.add_column('tasks', sa.Column('archived_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_users_archived', 'tasks', 'users', ['archived_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_archived', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'archived_by')
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['mapper_id', 'is_closed'], unique=False)
    # ### end Alembic commands ###
