"""empty message

Revision ID: 22e9a0e9b254
Revises: 772aff899389
Create Date: 2019-11-21 04:20:16.572298

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "22e9a0e9b254"
down_revision = "772aff899389"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "organisation_user_key", "organisation_managers", ["organisation_id", "user_id"]
    )
    op.create_unique_constraint("organisations_name_key", "organisations", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("organisation_user_key", "organisation_managers", type_="unique")
    op.drop_constraint("organisations_name_key", "organisations", type_="unique")
    # ### end Alembic commands ###
