"""empty message

Revision ID: 2b89f3ff0d9b
Revises: dc250d726600
Create Date: 2017-05-29 11:14:47.692968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b89f3ff0d9b'
down_revision = 'dc250d726600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas_of_interest')
    op.drop_constraint('projects_aoi_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'aoi_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('aoi_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_aoi_id_fkey', 'projects', 'areas_of_interest', ['aoi_id'], ['id'])
    op.create_table('areas_of_interest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326), autoincrement=False, nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='areas_of_interest_pkey')
    )
    # ### end Alembic commands ###
