"""empty message

Revision ID: 2cfa981c70e7
Revises: 5053c01cb170
Create Date: 2020-07-16 10:30:59.885956

"""
from alembic import op
import geoalchemy2

# revision identifiers, used by Alembic.
revision = "2cfa981c70e7"
down_revision = "5053c01cb170"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "centroid",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "geometry",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "geometry",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=True,
    )
    op.alter_column(
        "projects",
        "centroid",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
