"""empty message

Revision ID: 2f4f488105c6
Revises: c40e1fdf6b70
Create Date: 2020-03-08 13:44:48.538746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f4f488105c6"
down_revision = "c40e1fdf6b70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_validation_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_validation_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###
