"""empty message

Revision ID: 305ed1974a42
Revises: b93421cec5bd
Create Date: 2017-03-14 14:14:22.746530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '305ed1974a42'
down_revision = 'b93421cec5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_areas_of_interest_centroid', table_name='areas_of_interest')
    op.drop_index('idx_areas_of_interest_geometry', table_name='areas_of_interest')
    op.add_column('projects', sa.Column('priority', sa.Integer(), nullable=True))
    op.alter_column('projects', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_tasks_geometry', table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_geometry', 'tasks', ['geometry'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('projects', 'priority')
    op.create_index('idx_areas_of_interest_geometry', 'areas_of_interest', ['geometry'], unique=False)
    op.create_index('idx_areas_of_interest_centroid', 'areas_of_interest', ['centroid'], unique=False)
    # ### end Alembic commands ###
