"""empty message

Revision ID: 39c0b1b67186
Revises: 9f5b73af01db
Create Date: 2017-05-22 17:23:07.799441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c0b1b67186'
down_revision = '9f5b73af01db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_id')
    op.drop_column('users', 'linkedin_id')
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###
