"""empty message

Revision ID: 3b8b0956b217
Revises: bcb474128817
Create Date: 2022-07-27 10:30:55.193989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b8b0956b217"
down_revision = "bcb474128817"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("progress_email_sent", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "progress_email_sent")
    # ### end Alembic commands ###
