"""empty message

Revision ID: 41e77e26c926
Revises: cdd3de0cd655
Create Date: 2017-04-06 10:21:17.574050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e77e26c926'
down_revision = 'cdd3de0cd655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_areas_of_interest_centroid', table_name='areas_of_interest')
    op.drop_index('idx_areas_of_interest_geometry', table_name='areas_of_interest')
    op.add_column('tasks', sa.Column('locked_by', sa.BigInteger(), nullable=True))
    op.add_column('tasks', sa.Column('mapped_by', sa.BigInteger(), nullable=True))
    op.add_column('tasks', sa.Column('validated_by', sa.BigInteger(), nullable=True))
    op.drop_index('idx_tasks_geometry', table_name='tasks')
    op.drop_constraint('fk_users', 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_users_locked', 'tasks', 'users', ['locked_by'], ['id'])
    op.create_foreign_key('fk_users_validator', 'tasks', 'users', ['validated_by'], ['id'])
    op.create_foreign_key('fk_users_mapper', 'tasks', 'users', ['mapped_by'], ['id'])
    op.drop_column('tasks', 'lock_holder_id')
    op.drop_column('tasks', 'task_locked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('lock_holder_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_users_mapper', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_users_validator', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_users_locked', 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_users', 'tasks', 'users', ['lock_holder_id'], ['id'])
    op.create_index('idx_tasks_geometry', 'tasks', ['geometry'], unique=False)
    op.drop_column('tasks', 'validated_by')
    op.drop_column('tasks', 'mapped_by')
    op.drop_column('tasks', 'locked_by')
    op.create_index('idx_areas_of_interest_geometry', 'areas_of_interest', ['geometry'], unique=False)
    op.create_index('idx_areas_of_interest_centroid', 'areas_of_interest', ['centroid'], unique=False)
    # ### end Alembic commands ###
