"""empty message

Revision ID: 48c3aed123cf
Revises: a7c617755721
Create Date: 2017-05-01 12:09:36.887823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c3aed123cf'
down_revision = 'a7c617755721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('splittable', sa.Boolean(), nullable=True))
    op.alter_column('tasks', 'x',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'y',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'zoom',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'zoom',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'y',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'x',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'splittable')
    # ### end Alembic commands ###
