"""empty message

Revision ID: 4b9fb4d3f349
Revises: 451f6bd05a19
Create Date: 2019-07-19 13:38:08.010157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b9fb4d3f349'
down_revision = '451f6bd05a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('id_presets', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'id_presets')
    # ### end Alembic commands ###
