"""empty message

Revision ID: 5053c01cb170
Revises: 5952780a577e
Create Date: 2020-06-09 13:51:18.754882
"""

from alembic import op

# revision identifiers, used by Alembic.

revision = "5053c01cb170"
down_revision = "5952780a577e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("campaigns_name_key", "campaigns", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("campaigns_name_key", "campaigns", type_="unique")
    # ### end Alembic commands ###
