"""empty message

Revision ID: 52a67f6cef20
Revises: 42c45e74752b
Create Date: 2023-07-06 12:26:39.420411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52a67f6cef20"
down_revision = "42c45e74752b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("osm_teams_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "osm_teams_id")
    # ### end Alembic commands ###
