"""empty message

Revision ID: 5488d1cbb1ea
Revises: 30b091260689
Create Date: 2018-11-07 00:38:13.265485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488d1cbb1ea'
down_revision = '30b091260689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_geometry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_geometry')
    # ### end Alembic commands ###
