"""empty message

Revision ID: 55790eeec3bf
Revises: 2d6a7ad4e1eb
Create Date: 2020-05-12 18:43:37.666725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "55790eeec3bf"
down_revision = "2d6a7ad4e1eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notifications", "date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "notifications", "unread_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "notifications", "user_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.drop_index("idx_notifications_user_id", table_name="notifications")
    op.create_index(
        "idx_task_history_project_id_user_id",
        "task_history",
        ["user_id", "project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_history_user_id"), "task_history", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_locked_by"), "tasks", ["locked_by"], unique=False)
    op.create_index(op.f("ix_tasks_mapped_by"), "tasks", ["mapped_by"], unique=False)
    op.create_index(
        op.f("ix_tasks_validated_by"), "tasks", ["validated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_validated_by"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_mapped_by"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_locked_by"), table_name="tasks")
    op.drop_index(op.f("ix_task_history_user_id"), table_name="task_history")
    op.drop_index("idx_task_history_project_id_user_id", table_name="task_history")
    op.create_index(
        "idx_notifications_user_id", "notifications", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.alter_column(
        "notifications", "user_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "notifications", "unread_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "notifications", "date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
