"""empty message

Revision ID: 5e711bf34755
Revises: 1579d24928e7
Create Date: 2020-06-13 22:52:41.595827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e711bf34755"
down_revision = "1579d24928e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_info", sa.Column("metrics", sa.String(), nullable=True))
    op.add_column(
        "project_info", sa.Column("quality_assurance", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_info", "quality_assurance")
    op.drop_column("project_info", "metrics")
    # ### end Alembic commands ###
