"""empty message

Revision ID: 7408ceebbef7
Revises: 30b091260689
Create Date: 2019-03-28 11:58:27.032457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7408ceebbef7'
down_revision = '30b091260689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('upload_policy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('textsearch_idx', 'project_info', ['text_searchable'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('textsearch_idx', table_name='project_info')
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.drop_table('project_files')
    # ### end Alembic commands ###
