"""empty message

Revision ID: 7435b0a865e6
Revises: 6612e4d6524c
Create Date: 2019-08-20 08:54:12.215666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7435b0a865e6"
down_revision = "6612e4d6524c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("featured", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "featured")
    # ### end Alembic commands ###
