"""

Create a table for linking partners and projects.
Create a table to maintain a log for all changes to these links.

Revision ID: 749a9ae35ce5
Revises: e8ffa33a9c18
Create Date: 2024-06-27 09:36:30.577884

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "749a9ae35ce5"
down_revision = "e8ffa33a9c18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_partners",
        sa.Column("project_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("partner_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "started_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name="project_partners_partners_fk"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="project_partners_projects_fk"
        ),
        sa.PrimaryKeyConstraint("project_id", "partner_id", name="project_partners_pk"),
    )

    op.create_table(
        "project_partners_history",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("partner_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "action_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("action", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "started_on_old", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ended_on_old", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "started_on_new", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ended_on_new", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="project_partners_history_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_partners")
    op.drop_table("project_partners_history")
    # ### end Alembic commands ###
