"""empty message

Revision ID: 772aff899389
Revises: 83eb4cbb0abd
Create Date: 2019-11-08 19:09:46.152809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "772aff899389"
down_revision = "83eb4cbb0abd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "expert_mode")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "expert_mode", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    # ### end Alembic commands ###
