"""empty message

Revision ID: 7991a7e1b88d
Revises: e0741bdfde1d
Create Date: 2017-05-30 17:19:55.061108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7991a7e1b88d'
down_revision = 'e0741bdfde1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_info', sa.Column('per_task_instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_info', 'per_task_instructions')
    # ### end Alembic commands ###
