"""empty message

Revision ID: 7d55a089b5bc
Revises: 64b682d53e23
Create Date: 2017-06-26 17:22:12.828934

"""
from alembic import op
import sqlalchemy as sa
from server.models.postgis.project import Project
from server.models.postgis.task import Task

# revision identifiers, used by Alembic.
revision = '7d55a089b5bc'
down_revision = '64b682d53e23'
branch_labels = None
depends_on = None

projects = Project.__table__
tasks = Task.__table__


def upgrade():
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('task_creation_mode', sa.Integer(), nullable=True))
    op.create_index('idx_geometry', 'projects', ['geometry'], unique=False, postgresql_using='gist')
    op.add_column('tasks', sa.Column('extra_properties', sa.Unicode(), nullable=True))

    for project in conn.execute(projects.select()):
        zooms = conn.execute(
            sa.sql.expression.select([tasks.c.zoom]).distinct(tasks.c.zoom)
                .where(tasks.c.project_id == project.id))
        zooms = zooms.fetchall()

        if len(zooms) == 1 and zooms[0] == (None,):
            op.execute(
                projects.update().where(projects.c.id == project.id)
                    .values(task_creation_mode=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_properties')
    op.drop_index('idx_geometry', table_name='projects')
    op.drop_column('projects', 'task_creation_mode')
    # ### end Alembic commands ###
