"""empty message

Revision ID: 820300669c23
Revises: e556e18d016d
Create Date: 2018-10-02 09:33:07.240386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820300669c23'
down_revision = 'e556e18d016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_files_project_id', table_name='project_files')
    op.drop_constraint('project_files_path_file_name_key', 'project_files', type_='unique')
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.create_unique_constraint('project_files_path_file_name_key', 'project_files', ['path', 'file_name'])
    op.create_index('ix_project_files_project_id', 'project_files', ['project_id'], unique=False)
    # ### end Alembic commands ###
