"""empty message

Revision ID: 824268a7a675
Revises: 251a7638da78
Create Date: 2018-10-08 15:54:19.964101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824268a7a675'
down_revision = '251a7638da78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'splittable', new_column_name='is_square')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_square', new_column_name='splittable')
    # ### end Alembic commands ###

