"""empty message

Revision ID: 897dfade8545
Revises: b93421cec5bd
Create Date: 2017-03-16 10:57:03.999825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '897dfade8545'
down_revision = 'b93421cec5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_info',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'locale')
    )
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_areas_of_interest_centroid', table_name='areas_of_interest')
    op.drop_index('idx_areas_of_interest_geometry', table_name='areas_of_interest')
    op.add_column('projects', sa.Column('priority', sa.Integer(), nullable=True))
    op.alter_column('projects', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_tasks_geometry', table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_geometry', 'tasks', ['geometry'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('projects', 'priority')
    op.create_index('idx_areas_of_interest_geometry', 'areas_of_interest', ['geometry'], unique=False)
    op.create_index('idx_areas_of_interest_centroid', 'areas_of_interest', ['centroid'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.drop_table('project_info')
    # ### end Alembic commands ###
