"""empty message

Revision ID: 8a6419f289aa
Revises: 2ee4bca188a9
Create Date: 2021-06-23 17:11:22.666814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a6419f289aa"
down_revision = "2ee4bca188a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("rapid_power_user", sa.Boolean(), nullable=True)
    )
    op.drop_index(
        "idx_task_validation_validator_status_composite",
        table_name="task_invalidation_history",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_task_validation_validator_status_composite",
        "task_invalidation_history",
        ["invalidator_id", "is_closed"],
        unique=False,
    )
    op.drop_column("projects", "rapid_power_user")
    # ### end Alembic commands ###
