"""Add task notifications in user settings

Revision ID: 9712d29e24c8
Revises: 2cfa981c70e7
Create Date: 2020-07-28 21:13:50.314323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9712d29e24c8"
down_revision = "2cfa981c70e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "tasks_notifications",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    conn = op.get_bind()
    update_user_settings = (
        "UPDATE users SET tasks_notifications = true where validation_message = true;"
    )
    conn.execute(update_user_settings)
    op.drop_column("users", "validation_message")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "validation_message",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    conn = op.get_bind()
    update_user_settings = (
        "UPDATE users SET validation_message = true where tasks_notifications = true;"
    )
    conn.execute(update_user_settings)
    op.drop_column("users", "tasks_notifications")
    # ### end Alembic commands ###
