"""Add task notifications in user settings

Revision ID: 9712d29e24c8
Revises: 2cfa981c70e7
Create Date: 2020-07-28 21:13:50.314323

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "9712d29e24c8"
down_revision = "2cfa981c70e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "validation_message",
        nullable=False,
        new_column_name="tasks_notifications",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "tasks_notifications",
        nullable=False,
        new_column_name="validation_message",
    )
    # ### end Alembic commands ###
