"""empty message

Revision ID: 9c8939d32039
Revises: 109c34db2e73
Create Date: 2017-03-10 11:17:41.866777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8939d32039'
down_revision = '109c34db2e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actionText', sa.String(), nullable=True),
    sa.Column('actionDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id', 'project_id'], ['tasks.id', 'tasks.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_history_composite', 'task_history', ['task_id', 'project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_history_composite', table_name='task_history')
    op.drop_table('task_history')
    # ### end Alembic commands ###
