"""empty message

Revision ID: 9cfc37381798
Revises: 29ff449d9f63
Create Date: 2017-03-29 16:39:05.168034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfc37381798'
down_revision = '29ff449d9f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('author_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'author_id')
    # ### end Alembic commands ###
