"""empty message

Revision ID: a572dc09c774
Revises: 9be7acffedc2
Create Date: 2017-04-11 14:23:01.138584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a572dc09c774'
down_revision = '9be7acffedc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('changeset_comment', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('entities_to_map', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('imagery', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('josm_preset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'josm_preset')
    op.drop_column('projects', 'imagery')
    op.drop_column('projects', 'entities_to_map')
    op.drop_column('projects', 'due_date')
    op.drop_column('projects', 'changeset_comment')
    # ### end Alembic commands ###
