"""empty message

Revision ID: a60315eb2654
Revises: f547382df31b
Create Date: 2019-10-07 17:30:36.504327

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "a60315eb2654"
down_revision = "f547382df31b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "enforce_validator_role",
        nullable=True,
        new_column_name="restrict_validation_role",
    )
    op.alter_column(
        "projects",
        "enforce_mapper_level",
        nullable=True,
        new_column_name="restrict_mapping_level_to_project",
    )
    op.alter_column(
        "projects",
        "allow_non_beginners",
        nullable=True,
        new_column_name="restrict_validation_level_intermediate",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "restrict_validation_role",
        nullable=True,
        new_column_name="enforce_validator_role",
    )
    op.alter_column(
        "projects",
        "restrict_mapping_level_to_project",
        nullable=True,
        new_column_name="enforce_mapper_level",
    )
    op.alter_column(
        "projects",
        "restrict_validation_level_intermediate",
        nullable=True,
        new_column_name="allow_non_beginners",
    )
    # ### end Alembic commands ###
