"""empty message

Revision ID: a9cbd2c6c213
Revises: bcdb7875bd1c
Create Date: 2022-11-04 09:18:31.672823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9cbd2c6c213"
down_revision = "bcdb7875bd1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_version",
        sa.Column("tag_name", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("tag_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_version")
    # ### end Alembic commands ###
