"""empty message

Revision ID: bcb474128817
Revises: 8b61ac59bc57
Create Date: 2022-07-03 10:46:56.075805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bcb474128817"
down_revision = "8b61ac59bc57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_task_validation_validator_status_composite",
        "task_invalidation_history",
        ["invalidator_id", "is_closed"],
        unique=False,
    )
    op.add_column(
        "team_members",
        sa.Column("join_request_notifications", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("teams_announcement_notifications", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE team_members SET join_request_notifications = false")
    op.execute("UPDATE users SET teams_announcement_notifications = false")
    op.alter_column("team_members", "join_request_notifications", nullable=False)
    op.alter_column("users", "teams_announcement_notifications", nullable=False)
    op.drop_column("users", "teams_notifications")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "teams_notifications",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "teams_announcement_notifications")
    op.drop_column("team_members", "join_request_notifications")
    op.drop_index(
        "idx_task_validation_validator_status_composite",
        table_name="task_invalidation_history",
    )
    # ### end Alembic commands ###
