"""empty message

Revision ID: c6c7cc5382f8
Revises: f276d7305d97
Create Date: 2018-12-13 19:58:32.785000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c7cc5382f8'
down_revision = 'f276d7305d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priorities', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_priority_project', 'priorities', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_priority_project', 'priorities', type_='foreignkey')
    op.drop_column('priorities', 'project_id')
    # ### end Alembic commands ###
