"""empty message

Revision ID: d01c4ceddeb4
Revises: df617df60678
Create Date: 2019-03-26 07:27:34.083130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd01c4ceddeb4'
down_revision = 'df617df60678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('mapping_editors', postgresql.ARRAY(sa.Integer()), nullable=False, server_default='{0,1,2,3}'))
    op.add_column('projects', sa.Column('validation_editors', postgresql.ARRAY(sa.Integer()), nullable=False, server_default='{0,1,2,3}'))
    op.create_index(op.f('ix_projects_mapping_editors'), 'projects', ['mapping_editors'], unique=False)
    op.create_index(op.f('ix_projects_validation_editors'), 'projects', ['validation_editors'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_validation_editors'), table_name='projects')
    op.drop_index(op.f('ix_projects_mapping_editors'), table_name='projects')
    op.drop_column('projects', 'validation_editors')
    op.drop_column('projects', 'mapping_editors')
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    # ### end Alembic commands ###
