"""empty message

Revision ID: d18171490fc0
Revises: 12eaf9720f72
Create Date: 2019-05-07 12:37:47.439918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18171490fc0'
down_revision = '12eaf9720f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('enforce_assignment', sa.Boolean(), nullable=True, server_default='False'))
    op.add_column('projects', sa.Column('enforce_random_task_selection', sa.Boolean(), nullable=True, server_default='False'))
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('projects', 'enforce_random_task_selection')
    op.drop_column('projects', 'enforce_assignment')
    # ### end Alembic commands ###
