"""empty message

Revision ID: d20adba635a0
Revises: e4c3a56adc7a
Create Date: 2018-05-16 19:25:46.954821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20adba635a0'
down_revision = '824268a7a675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_geometry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_geometry')
    # ### end Alembic commands ###
