"""empty message

Revision ID: d31d89148484
Revises: a9cbd2c6c213
Create Date: 2022-12-01 11:53:54.513994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d31d89148484"
down_revision = "a9cbd2c6c213"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application_keys", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("priority_areas", schema=None) as batch_op:
        batch_op.create_index(
            "idx_priority_areas_geometry",
            ["geometry"],
            unique=False,
            postgresql_using="gist",
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            "idx_projects_centroid", ["centroid"], unique=False, postgresql_using="gist"
        )
        batch_op.create_index(
            "idx_projects_geometry", ["geometry"], unique=False, postgresql_using="gist"
        )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tasks_geometry", ["geometry"], unique=False, postgresql_using="gist"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("idx_tasks_geometry", postgresql_using="gist")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("idx_projects_geometry", postgresql_using="gist")
        batch_op.drop_index("idx_projects_centroid", postgresql_using="gist")

    with op.batch_alter_table("priority_areas", schema=None) as batch_op:
        batch_op.drop_index("idx_priority_areas_geometry", postgresql_using="gist")

    with op.batch_alter_table("application_keys", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###
