"""empty message

Revision ID: d357fe2dd332
Revises: 4329c80632e1
Create Date: 2017-04-18 10:42:39.308450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd357fe2dd332'
down_revision = '4329c80632e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('tasks_mapped', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('tasks_validated', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('total_tasks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_tasks')
    op.drop_column('projects', 'tasks_validated')
    op.drop_column('projects', 'tasks_mapped')
    op.drop_column('projects', 'last_updated')
    # ### end Alembic commands ###
