"""Adding extra_properties column to tasks

Revision ID: d3ed291041a3
Revises: 64b682d53e23
Create Date: 2017-06-20 11:57:02.949895

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd3ed291041a3'
down_revision = '64b682d53e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks',
                  sa.Column('extra_properties', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_properties')
    # ### end Alembic commands ###
