"""empty message

Revision ID: d44063d20a3b
Revises: 9f5b73af01db
Create Date: 2017-05-23 16:30:53.118269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44063d20a3b'
down_revision = '9f5b73af01db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_address_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_id')
    op.drop_column('users', 'linkedin_id')
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'email_address_verified')
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###
