"""add parameter seq_page_cost and random_page_cost

Revision ID: da539cedc6c0
Revises: 9712d29e24c8
Create Date: 2020-08-05 23:28:26.923413

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "da539cedc6c0"
down_revision = "9712d29e24c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        "ALTER TABLESPACE pg_default SET(seq_page_cost=1.0, random_page_cost=1.0);"
    )
    # ### end Alembic commands ###


def downgrade():
    pass
