"""empty message

Revision ID: e36f1d0c4947
Revises: badf8bb7d56b
Create Date: 2019-06-14 11:20:15.129237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e36f1d0c4947"
down_revision = "badf8bb7d56b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_annotations", sa.Column("annotation_markdown", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_annotations", "annotation_markdown")
    # ### end Alembic commands ###
