"""empty message

Revision ID: e556e18d016d
Revises: 1266b3e5fc96
Create Date: 2018-10-01 15:07:50.495920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e556e18d016d'
down_revision = '1266b3e5fc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_files', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_project_files_project_id', table_name='project_files')
    op.drop_constraint('project_files_path_file_name_key', 'project_files', type_='unique')
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.create_unique_constraint('project_files_path_file_name_key', 'project_files', ['path', 'file_name'])
    op.create_index('ix_project_files_project_id', 'project_files', ['project_id'], unique=False)
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    # op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.create_unique_constraint('project_files_path_file_name_key', 'project_files', ['path', 'file_name'])
    op.create_index('ix_project_files_project_id', 'project_files', ['project_id'], unique=False)
    op.alter_column('project_files', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
