"""empty message

Revision ID: e8ffa33a9c18
Revises: 42c45e74752b
Create Date: 2024-06-07 20:20:49.591011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e8ffa33a9c18"
down_revision = "42c45e74752b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("primary_hashtag", sa.String(length=50), nullable=False),
        sa.Column("secondary_hashtag", sa.String(length=50), nullable=True),
        sa.Column("logo_url", sa.String(length=100), nullable=True),
        sa.Column("link_meta", sa.String(length=50), nullable=True),
        sa.Column("link_x", sa.String(length=50), nullable=True),
        sa.Column("link_instagram", sa.String(length=50), nullable=True),
        sa.Column("current_projects", sa.String(), nullable=True),
        sa.Column("permalink", sa.String(length=250), nullable=True),
        sa.Column("website_links", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("permalink"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partners")
    # ### end Alembic commands ###
