""" Add mapswipe group ID to partners table

Revision ID: ecb6985693c0_
Revises: 749a9ae35ce5
Create Date: 2024-12-04 19:53:41.477085

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecb6985693c0_"
down_revision = "749a9ae35ce5"
branch_labels = None
depends_on = None


def upgrade():
    # ### end Alembic commands ###
    op.add_column(
        "partners", sa.Column("mapswipe_group_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partners", "mapswipe_group_id")
    # ### end Alembic commands ###
