"""empty message

Revision ID: ee46f5e8723b
Revises: 451f6bd05a19
Create Date: 2019-07-14 16:27:37.368109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee46f5e8723b"
down_revision = "451f6bd05a19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("irc_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("city", sa.String(), nullable=True))
    op.add_column("users", sa.Column("country", sa.String(), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("skype_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("slack_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "slack_id")
    op.drop_column("users", "skype_id")
    op.drop_column("users", "city")
    op.drop_column("users", "country")
    op.drop_column("users", "name")
    op.drop_column("users", "irc_id")
    # ### end Alembic commands ###
