"""empty message

Revision ID: f276d7305d97
Revises: bb6531c477f5
Create Date: 2018-04-18 06:03:58.025882

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f276d7305d97'
down_revision = '30b091260689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key('fk_users_uploader', 'priorities', 'users', ['uploaded_by'], ['id'])

    op.add_column('projects', sa.Column('selected_priorities', postgresql.ARRAY(sa.Integer()), nullable=True))

    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priorities')
    op.drop_column('projects', 'selected_priorities')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
