"""empty message

Revision ID: f547382df31b
Revises: 068674f06b0f
Create Date: 2019-10-07 07:06:12.394963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f547382df31b"
down_revision = "068674f06b0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("gender", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("self_description_gender", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "self_description_gender")
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
