"""empty message

Revision ID: f86698c827cc
Revises: e3282e2db2d7
Create Date: 2019-11-06 11:46:48.616033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f86698c827cc"
down_revision = "e3282e2db2d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    op.drop_index("ix_projects_campaign_tag", table_name="projects")
    op.drop_column("projects", "campaign_tag")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("campaign_tag", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_projects_campaign_tag", "projects", ["campaign_tag"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("organisations", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("campaigns", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="tags_pkey"),
        sa.UniqueConstraint("campaigns", name="tags_campaigns_key"),
        sa.UniqueConstraint("organisations", name="tags_organisations_key"),
    )
    # ### end Alembic commands ###
