""" add exempt field to organisation model

Revision ID: f9806b2e87ce
Revises: 7937dae319b5
Create Date: 2021-02-05 12:31:29.095497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9806b2e87ce"
down_revision = "7937dae319b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organisations", sa.Column("exempt", sa.Boolean(), nullable=True))
    op.execute("UPDATE organisations SET exempt = true")
    op.alter_column("organisations", "exempt", nullable=False)
    op.drop_index(
        "idx_task_validation_mapper_status_composite",
        table_name="task_invalidation_history",
    )
    op.create_index(
        "idx_task_validation_mapper_status_composite",
        "task_invalidation_history",
        ["mapper_id", "is_closed"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_task_validation_mapper_status_composite",
        table_name="task_invalidation_history",
    )
    op.create_index(
        "idx_task_validation_mapper_status_composite",
        "task_invalidation_history",
        ["invalidator_id", "is_closed"],
        unique=False,
    )
    op.drop_column("organisations", "exempt")
    # ### end Alembic commands ###
