export const getProjectSummary = (id) => ({
  projectId: id,
  defaultLocale: 'en',
  author: 'test_user',
  created: '2019-08-27T12:18:07.186897Z',
  dueDate: '2020-04-07T12:20:42.460024Z',
  lastUpdated: '2020-06-22T10:16:16.076317Z',
  projectPriority: 'URGENT',
  campaigns: [
    {
      id: 3,
      name: 'Environment Conservation',
    },
    {
      id: 5,
      name: 'Women security',
    },
  ],
  organisation: 32,
  organisationName: 'HOT',
  organisationLogo: 'https://www.missingmaps.org/assets/graphics/content/logos/hot_logo.png',
  countryTag: ['Bolivia'],
  osmchaFilterId: '9322aa63-cccc-4d0d-9f93-403678e52345',
  mappingTypes: ['BUILDINGS'],
  changesetComment: `#hotosm-project-${id} #brumado-buildings`,
  percentMapped: 16,
  percentValidated: 6,
  percentBadImagery: 0,
  aoiCentroid: {
    type: 'Point',
    coordinates: [-41.669134813, -14.20341561],
  },
  mapperLevel: 'BEGINNER',
  mappingPermission: 'LEVEL',
  validationPermission: 'LEVEL',
  allowedUsernames: [],
  enforceRandomTaskSelection: false,
  private: false,
  teams: [],
  projectInfo: {
    locale: 'en',
    name: 'La Paz Buildings',
    shortDescription: 'La Paz buildings mapping  [here](http://localhost:8111/import).',
    description: 'La Paz buildings mapping  [here](http://localhost:8111/import).',
    instructions:
      'Project Specific Mapping Notes: Bing appears to be the best imagery for the area, you may need to align it with GPS or existing roads, but will likely need to adjust the roads with this better/most recent imagery.* `Please improve existing incorrectly mapped elements by moving and adjusting, rather than deleting, if they do not line up with the imagery.`',
    perTaskInstructions:
      'This task involves loading extra data. Click [here](http://localhost:8111/import?new_layer=true&amp;url=http://www.domain.com/data/{x}/{y}/{z}/routes_2009.osm) to load the data into JOSM.',
  },
  shortDescription: null,
  status: 'PUBLISHED',
  imagery: null,
  licenseId: null,
  idPresets: ['building/house', 'building/residential', 'building'],
  mappingEditors: ['ID', 'JOSM'],
  validationEditors: ['JOSM', 'POTLATCH_2', 'FIELD_PAPERS'],
});

export const getProjectStats = (id) => ({
  projectId: id,
  'projectArea(in sq.km)': 3506.03997973834,
  totalMappers: 105,
  totalTasks: 2779,
  totalComments: 47,
  totalMappingTime: 2186584,
  totalValidationTime: 589857,
  totalTimeSpent: 2776441,
  averageMappingTime: 679.2743087915502,
  averageValidationTime: 202.14427690198767,
  percentMapped: 100,
  percentValidated: 100,
  percentBadImagery: 0,
  aoiCentroid: {
    type: 'Point',
    coordinates: [-7.56545195794146, 13.0603087530714],
  },
  timeToFinishMapping: 0,
  timeToFinishValidating: 0,
});
