#cloud-config
package_update: true
package_upgrade: true

packages:
  - jq
  - unzip

runcmd:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - |
    CONNECT_KEY=$(aws secretsmanager get-secret-value --secret-id ${JUMPCLOUD_CONNECT_KEY_ARN} | jq -r .SecretString) && \
    curl --tlsv1.2 --silent --show-error --header "x-connect-key: $CONNECT_KEY" https://kickstart.jumpcloud.com/Kickstart | sudo bash
