name: Build & publish TM backend container image

on:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  backend-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.5.1
    with:
      image_name: ghcr.io/${{ github.repository }}/backend
      build_target: prod
      dockerfile: scripts/docker/Dockerfile
