name: Build & publish TM backend container image

on:
  push:
    branches:
      - deployment/hot-tasking-manager
      - deployment/demo-tasking-manager
      - deployment/container-tasking-manager

  pull_request:
    branches:
      - main
      - staging
      - develop
      - deployment/hot-tasking-manager
      - deployment/demo-tasking-manager
      - deployment/container-tasking-manager

jobs:
  backend-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.5.1
    with:
      image_name: ghcr.io/${{ github.repository }}/backend
      build_target: prod
