name: 🔧 Build CI Img

on:
  # Push includes PR merge
  push:
    branches:
      - main
      - staging
      - development
    paths:
      # Workflow is triggered only if deps change
      - "src/backend/pyproject.toml"
      - "src/backend/Dockerfile"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  backend-ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.2.0
    with:
      context: .
      build_target: ci
      image_tags: |
        "ghcr.io/${{ github.repository }}/backend:ci-${{ github.ref_name }}"

  invalidate-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete CI Img Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete image-cache-${{ runner.os }} \
            -R ${{ github.repository }} \
            -B ${{ github.ref_name }} \
            --confirm || true
