name: Build & publish TM backend container image

on:
  push:
    branches:
      - deployment/hot-tasking-manager
      - deployment/demo-tasking-manager
      - deployment/container-tasking-manager

  pull_request:
    branches:
      - main
      - staging
      - develop
      - deployment/hot-tasking-manager
      - deployment/demo-tasking-manager
      - deployment/container-tasking-manager

jobs:
  build:
    name: Build Static Files
    runs-on: ubuntu-latest

    environment:
      name: develop
      url: "https://just.build.test"

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: tm-fe-${{ runner.os }}-build-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            tm-fe-${{ runner.os }}-build-${{ hashFiles('frontend/package.json') }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Load Environment from GitHub variables & secrets.
        uses: hotosm/gh-workflows/.github/actions/vars_n_secret_to_env@env_substitute/1.0.0
        with:
          vars_context: ${{ toJson(vars) }}
          secrets_context: ${{ toJson(secrets) }}

      - name: Create .env file
        uses: hotosm/gh-workflows/.github/actions/env_substitute@env_substitute/1.0.0
        with:
          working_directory: ./frontend
          template_dotenv: .env.expand
          output_file: .env

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Generate build
        working-directory: ./frontend
        run: |
          yarn build
