name: Generación de Reportes de Pruebas

on:
  pull_request:
    branches:
      - develop

jobs:
  prueba-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Verificar Docker
        run: |
          docker --version
          docker compose version