name: Terragrunt Apply

on:
  workflow_dispatch:
    inputs:
      plan_file_name:
        description: "Enter Terragrunt Plan File name in s3 to run"
        required: true

jobs:
  apply:
    uses: naxa-developers/gh-workflows/.github/workflows/apply.yml@master
    with:
      working_dir: ./scripts/aws/infra/dev/purgeable/ecs
      terraform_version: "1.9.5"
      terragrunt_version: "0.67.15"
      aws_region: us-west-2
      plan_file_name: ${{ inputs.plan_file_name }}
    secrets: inherit
