name: Terragrunt Apply

on:
  workflow_dispatch:
    inputs:
      plan_file_name:
        description: "Enter Terragrunt Plan File name to run"
        required: true

jobs:
  apply:
    uses: naxa-developers/gh-workflows/.github/workflows/terragrunt-apply.yml@v0.4
    with:
      working_dir: ./scripts/aws/infra/staging/purgeable/ecs/
      terraform_version: "1.9.5"
      terragrunt_version: "0.67.15"
      aws_region: us-west-2
      plan_file_name: ${{ inputs.plan_file_name }}
      use_gh_artifacts: true
    secrets: inherit
