name: Terragrunt Apply

on:
  workflow_dispatch:
    inputs:
      module_path:
        description: "Select Terragrunt Module to run"
        required: true
        type: choice
        default: purgeable/ecs/
        options:
          - purgeable/ecs/
          - non-purgeable/extras/
      plan_file_name:
        description: "Enter Terragrunt Plan File name to run"
        required: true

jobs:
  # workaround for using GHActions environment variables feature. In future we can use ${{ github.ref_name }} directly in the workflow as INFRA_BRANCH
  get_deployment_meta:
    runs-on: ubuntu-latest
    outputs:
      INFRA_BRANCH: ${{ steps.get_deployment_meta.outputs.INFRA_BRANCH }}
    steps:
      - name: Get Deployment Meta
        id: get_deployment_meta
        shell: bash
        run: |
          case "${{ github.ref }}" in
          refs/heads/tasking-manager-fastapi)
            export INFRA_BRANCH=staging
            ;;
          esac
          echo "INFRA_BRANCH=${INFRA_BRANCH}" >> $GITHUB_OUTPUT

  apply:
    uses: naxa-developers/gh-workflows/.github/workflows/terragrunt-apply.yml@v0.4
    needs:
      - get_deployment_meta
    with:
      working_dir: ./scripts/aws/infra/${{ needs.get_deployment_meta.outputs.INFRA_BRANCH }}/${{ github.event.inputs.module_path }}
      terraform_version: "1.9.5"
      terragrunt_version: "0.67.15"
      aws_region: us-west-1
      plan_file_name: ${{ inputs.plan_file_name }}
      use_gh_artifacts: true
    secrets: inherit
